echo "" > nue.js
cat src/utils.js >> nue.js
cat src/vector.js >> nue.js
cat src/event.js >> nue.js
cat src/ref.js >> nue.js
cat src/template.js >> nue.js
cat src/component.js >> nue.js
cat src/tags.js >> nue.js
cat src/honest-table.js >> nue.js
cat src/paned-frame.js >> nue.js
cat src/filter.js >> nue.js
cat src/notebook.js >> nue.js
cat src/slide-show.js >> nue.js
cat src/dropdown.js >> nue.js
cat src/test.js >> nue.js
